language: node_js

notifications:
  email: false

node_js:
  - '7'
  - '6'

services:
  - postgresql

addons:
  postgresql: '9.5'

before_script:
  - psql -c 'create database graphql_tower;' -U postgres
  - npm prune
  - npm run bootstrap

after_success:
  - npm run deploy

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
