language: node_js

notifications:
  email: false

node_js:
  - '7'
  - '6'
  - '4'

services:
  - postgresql

addons:
  postgresql: '9.5'

before_script:
  - psql -c 'create database graphql-tower;' -U postgres
  - npm prune

after_success:
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
